### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by mrzjaman** [Sansel-Tech/sdalloc#1]
why don't we use assert instead of 
if (ptr == NULL) {
	fprintf(stderr, "sdmalloc: failed due to %s\n", strerror(errno));
	abort();
	return NULL; /* not_reachable */
}

Thanks
Jaman

**Comment by kribakarans** [comment]
Calling ```assert()``` is fine but in negative case (if sdallocs failed) we might have multiple things to do like logging, closing files, freeing memory that allocated to some other pointers earlier and more.
So, we are doing it in separate if-else context.

**Comment by mrzjaman** [comment]
Got it, Thanks for your valuable reply

Regards,
Jaman
