### ISSUE TITLE
Abort [SIGABRT]

### ISSUE THREAD

**Issue by littlemaster1612** [Sansel-Tech/sdalloc#2]
Abort producing an abnormal program termination. Still it needed ?
After abort using break is really needed ?
```
do {
	if (s == NULL) {
		fprintf(stderr, "sdstrdup: NULL input !!!\n");
		abort();
		break;
        }
    ....
```

**Comment by kribakarans** [comment]
Correct, ```abort()``` will do abnormal termination by SIGABRT signal. This will not close files and not flush stream buffers.
Finally, kernel will dump the core files with this details also the stack trace. This will help us to debug the crash. 
If we do the ```exit()```, kernel will treat as graceful exit and we cannot find the crash.
